### ISSUE TITLE
You can use Polars for data manipulation.

### ISSUE THREAD

**Issue by rts-gordon** [haixuanTao/Data-Manipulation-Rust-Pandas#1]
Polars: https://github.com/pola-rs/polars

**Comment by haixuanTao** [comment]
Yes,

I covered polars in another thread: https://able.bio/haixuanTao/data-manipulation-polars-vs-rust--3def44c8

with another repo: https://github.com/haixuanTao/dataframe-python-rust

Thanks anyway :)
